model = "waveletflow"
stepsPerResolution = [8] * 7
stepsPerResolution_L = [4] * 7
nLevels = 6
kernel = 3
baseLevel = 1
partialLevel = -1
hiddenChannels = 64
n_res_blocks = 3
actNormScale = 1.0
imShape = [1, 64, 64]
perm = "invconv"
coupling = "checker"
y_classes = None
y_learn_top = False
y_condition = False
y_weight = None
conditional = True
LU = True
dataset = 'agora'
gauss_priors = [1, 2]