model = "waveletflow"
stepsPerResolution = [32] * 8
stepsPerResolution_L = [3] * 8
normalize = [False] * 10
nLevels = 6
kernel = 3
baseLevel = 1
partialLevel = -1
hiddenChannels = 256
n_res_blocks = 3
actNormScale = 1.0
imShape = [2, 64, 64]
perm = "invconv"
coupling = "checker"
y_classes = None
y_learn_top = False
y_condition = False
y_weight = None
conditional = True
LU = True
dataset = 'My_lmdb'
gauss_priors = [1,2,3,4,5] #set this for HCC prior. For WN prior, add all the layers to this list
priorType = 'CC' #Choose 'CC' or 'C'
dataset_path = '/sdf/group/kipac/users/mati/yuuki_sim_train_64x64/'
val_dataset_path = '/sdf/group/kipac/users/mati/yuuki_sim_val_64x64/'
std_path = 'norm_stds/final_mean_stats_all_levels_noise_0.4.json'
ps_path = 'ps/noised_0.4_sim_kapcib_dwtlevel'
saveDir = '/sdf/group/kipac/users/mati/cc_prior_noised_yuuki_sims_all_levels_unnorm_checker_agora2/'
plotSaveDir = 'plots_cc_target_cond_checker_all_levels_unnorm_agora2/' 