model = "waveletflow"
stepsPerResolution = [2, 2, 4, 8, 16, 16, 16, 16, 16, 16, 16]
stepsPerResolution_L = [3] * 8
normalize = [False] * 10
nLevels = 8
kernel = 3
baseLevel = 1
partialLevel = -1
hiddenChannels = 256
n_res_blocks = 3
actNormScale = 1.0
imShape = [2, 256, 256]
perm = "invconv"
coupling = "checker"
y_classes = None
y_learn_top = False
y_condition = False
y_weight = None
conditional = True
LU = True
dataset = 'yuuki_256'
gauss_priors = [1,2,3,4,5,6,7] #set this for HCC prior. For WN prior, add all the layers to this list
priorType = 'CC' #Choose 'CC' or 'C'
dataset_path = '/sdf/group/kipac/users/mati/yukki_kap_cib_256x256/'
val_dataset_path = '/sdf/group/kipac/users/mati/yukki_kap_cib_256x256/'
std_path = 'norm_stds/256x256_final_mean_stats_all_levels_noise_0.025.json'
ps_path = 'ps/256x256_noised_0.025_sim_kapcib_dwtlevel'
saveDir = '/sdf/group/kipac/users/mati/HCC_prior_best_model_256/'
plotSaveDir = 'plots_HCC_prior_best_model_256/' 